// import type { Metadata } from "next";
import React from 'react';
import { ThemeProvider } from '@mui/material/styles';
import theme from './theme';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
        <ThemeProvider theme={theme}>
          {children}
        </ThemeProvider>
  );
}

export default RootLayout;